### PR TITLE
Make Tuples amenable to destructuring declarations

### PR DESCRIPTION
**Pull request by dynaxis**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@dynaxis Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-kotlin&pullRequestId=3)!

[Click here](https://cla.pivotal.io/sync/reactor?repositoryId=reactor/reactor-kotlin&pullRequestId=3) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@dynaxis Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-kotlin&pullRequestId=3)!

**Comment by dynaxis** [comment]
I put the extension functions to `Tuple`s in `reactor.util.function` package, where `Tuple`s reside. The current `Flux` extensions are put into the default package, which I'm not sure is a good practice. FYI, RxKotlin seems putting extension functions to its own, RxKotlin specific packages.

**Comment by sdeleuze** [comment]
Good point I will change that, that's a mistake.

**Pull request merged**
