### PR TITLE
Extension function toMono() can be invoked on nullable type

### PR DESCRIPTION
**Pull request by karolkrasnowski**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@karolkrasnowski Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-kotlin-extensions&pullRequestId=15)!

[Click here](https://cla.pivotal.io/sync/reactor?repositoryId=reactor/reactor-kotlin-extensions&pullRequestId=15) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@karolkrasnowski Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-kotlin-extensions&pullRequestId=15)!

**Comment by sdeleuze** [comment]
That's a good one IMO, :+1: for merging it.

**Review by simonbasle — APPROVED** [review]

**Comment by simonbasle** [comment]
Thanks for the PR @karolkrasnowski, sorry it fell through the cracks of the Nov. release. This will be released in 1.1.1 next week.

**Pull request merged**
