### PR TITLE
Some more extensions to make working with StepVerifier a bit easier

### PR DESCRIPTION
**Pull request by yevgeniy-kovalev**
and more concise

Some additional formatting was done by IDEA's auto-format.

### CODE REVIEW

**Comment by sdeleuze** [comment]
Hey @yevgeniy-kovalev, sorry for the lag I missed that PR.

Interesting proposal, could you please rework this PR to integrate only the `StepVerifier` based extensions without the style change ? That would make it easier for me to review it and if we do style change I prefer to isolate it in a distinct commit.

**Comment by pivotal-issuemaster** [comment]
@yevgeniy-kovalev Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-kotlin&pullRequestId=1)!

[Click here](https://cla.pivotal.io/sync/reactor?repositoryId=reactor/reactor-kotlin&pullRequestId=1) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by yevgeniy-kovalev** [comment]
Hey @sdeleuze!
No problems with lag, it's OK.
Could you please provide more details about 'integrate only the `StepVerifier` based extensions'? I mean, do you see it as removing all the new code from `FluxExtensions` and `MonoExtensions` or should the code be partially moved to `StepVerifierExtensions`?
As for formatting, it's just standard IDEA's one, so I'll remove it.
No offence here, just curious. Honestly, I'm not really experienced API writer, that's why there is a question :)

**Comment by sdeleuze** [comment]
In a nutshell please isolate changes in different commits, so please:
 - Create a commit for `StepVerifierExtensions` changes
 - Create other commits for `MonoExtensions` and  `FluxExtensions`

**Comment by pivotal-issuemaster** [comment]
@yevgeniy-kovalev Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-kotlin&pullRequestId=1)!

**Comment by sdeleuze** [comment]
After reviewing your PR, I have decided to not integrate it because it duplicates some functions already available in Reactor Core (like `verifyError()`). Be aware I have integrated various fixes in `master` and I will continue to integrate other Kotlin extensions in the upcoming days.

Thanks for your contribution.

**Comment by sdeleuze** [comment]
@yevgeniy-kovalev Could you have a quick look to the `.test()` extension I have just added to `master`?

**Comment by yevgeniy-kovalev** [comment]
Yeah, looks good! Definitely more expressive than mine.

**Pull request closed without merging**
